---
ogs:
  repo: "https://github.com/open5gs/open5gs"
  version: main

hplmn:
  config_repo: https://github.com/Open5GS-Configs/HPLMN-Config
  hosts_path: /home/agustin/hosts/hplmn/hosts
  test_script: /home/agustin/tests/hplmn_test.sh
  private_ip: "10.10.0.3"
  region: "yto"

vplmn:
  config_repo: https://github.com/Open5GS-Configs/VPLMN-Config
  hosts_path: /home/agustin/hosts/vplmn/hosts
  test_script: /home/agustin/tests/vplmn_test.sh
  private_ip: "10.10.0.4"
  region: "yto"

vultr:
  vpc:
    v4_subnet: "10.10.0.0"
    v4_subnet_mask: "28"
    region: "yto"
  plan_id: "vc2-2c-2gb"
  api_key: "IWDH7B6ZFLZ5HSRUITDNJVJFEVA747HUFE2Q"

create_services: true
user_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILtDJ010ycSBEjoVu8XP2ob/z20TCd5xqsIUpNaielao root@DESKTOP-6QUR9Q3"
provider: "Vultr"