interface_num: 2
private_ip: 
	sepp_link:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
	:
  interface: enp8s0
  ip: 10.10.0.3
topssim_hplmn:
  interface: enp9s0
  ip: 10.20.0.5

ogs: True

ogs_repo: https://github.com/open5gs/open5gs
ogs_version: main
use_config_path: False

config_repo: https://github.com/Open5GS-Configs/HPLMN-Config

use_hosts_path: True

hosts_path: /home/agustin/hosts/hplmn/hosts


