---

- name: Copy service files 
  ansible.builtin.copy:
    src: files/
    dest: /etc/systemd/system
  when: (inventory_hostname in groups['hplmn']) or inventory_hostname in groups['vplmn']

- name: Copy HPLMN SEPP service file
  ansible.builtin.copy:
    src: /etc/systemd/system/hplmn/open5gs-seppd.service
    dest: /etc/systemd/system
    remote_src: true
  when: inventory_hostname in groups['hplmn']

- name: Copy VPLMN SEPP service file
  ansible.builtin.copy:
    src: /etc/systemd/system/vplmn/open5gs-seppd.service
    dest: /etc/systemd/system
    remote_src: true
  when: inventory_hostname in groups['vplmn']

- name: Remove unnecessary folder (HPLMN)
  ansible.builtin.file:
    path: /etc/systemd/system/hplmn/
    state: absent
  when: (inventory_hostname in groups['hplmn']) or inventory_hostname in groups['vplmn']

- name: Remove unnecessary folder (VPLMN)
  ansible.builtin.file:
    path: /etc/systemd/system/vplmn/
    state: absent
  when: (inventory_hostname in groups['hplmn']) or inventory_hostname in groups['vplmn']

- name: Force systemd to reread configs 
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: (inventory_hostname in groups['hplmn']) or inventory_hostname in groups['vplmn']

- name: Make sure service is running and enable it 
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: "{{ item }}"
  loop: "{{ services }}"
  when: (inventory_hostname in groups['hplmn']) or inventory_hostname in groups['vplmn']
