- name: Installation Stage
  hosts: all
  roles:
    - mongodb_repository
    - mongodb_install
    - Open5GS Setup

  vars:
    - specific_mongodb_version: 8.0.23

- name: Configuration Stage:
  hosts: all
  roles:
    - Open5GS Config
    - Netplan Config
