- name: Wait for SSH
  hosts: all
  tags: install_stage, config_stage, testing_stage
  gather_facts: false
  tasks:
    - name: Wait for SSH to become available
      ansible.builtin.wait_for_connection:
        timeout: 300
        sleep: 5

- name: Installation Stage
  hosts: all
  tags: install_stage
  roles:
    - MongoDB Install
    - Open5GS Setup
  vars:
    specific_mongodb_version: "8.0.23"
    node_major: 20 # used for the installation of NodeJS

- name: Configuration Stage
  hosts: all
  tags: config_stage
  roles:
    - Open5GS Config
    - role: Netplan Config
      when: provider == "vultr"
  vars:
    enp8s0_block: |
      - "{{ private_ip }}/{{ vpc_v4_subnet_mask }}"
    eth1_block: |
      - "{{ private_ip }}/24"

- name: Create Services
  hosts: all
  tags: services_stage
  vars_files:
    - vars/vars.yaml
  roles: 
    - role: Create Services
      when: create_services
  become: yes

- name: Testing Stage
  hosts: all
  tags: testing_stage
  vars_files:
    - vars/vars.yaml
  tasks:
    #- name: Test 5G core with builtin tests
    #  ansible.builtin.command: 
    #    cmd: ./build/tests/registration/registration -c /root/open5gs/build/configs/sample.yaml simple-test
    #    chdir: /root/open5gs

    - name: Run HPLMN test script
      ansible.builtin.script: "{{ hplmn_test_script }}"
      register: hplmn_test
      when: inventory_hostname in groups['hplmn']
      timeout: "{{ test_command_timeout }}"

    - name: Print HPLMN test command output
      ansible.builtin.debug:
        var: hplmn_test
      when: inventory_hostname in groups['hplmn']

    - copy:
        src: "{{ vplmn_test_script }}"
        dest: /tmp/vplmn_test.sh
        mode: '0755'

    - name: Run VPLMN test script
      ansible.builtin.shell:
        cmd: /tmp/vplmn_test.sh
      async: "{{ test_command_timeout }}"
      poll: 5
      register: vplmn_test
      when: inventory_hostname in groups['vplmn']

    - name: Print VPLMN test command output
      ansible.builtin.debug:
        var: vplmn_test
      when: inventory_hostname in groups['vplmn']
  become: yes


