# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'


vars = YAML.load_file("vars.yaml")
boxes = vars["boxes"].keys


#inventory = {}
Vagrant.configure("2") do |config|

  config.vm.boot_timeout = 600

  config.vm.box = "bento/ubuntu-24.04"
 
  config.vm.box_version = "202510.26.0"
  
  user_ssh_key = vars["general"]["user_ssh_key"]
  ansible_ssh_key = vars["general"]["ansible_ssh_key"]
 
  config.vm.provision "shell", inline: <<-SHELL
    cat > /home/vagrant/.ssh/authorized_keys <<EOF
    #{user_ssh_key}
    #{ansible_ssh_key}
    EOF

    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
  SHELL

  provider = vars["general"]["provider"]
  config.vm.provision "shell", path: "install_python.sh"

  boxes.each do |box|
    config.vm.define "#{box}" do |machine|
      machine.vm.hostname = vars["boxes"][box]["hostname"]
      
      machine.disksize.size = "#{vars["boxes"][box]["disk"]}GB"
      
      if provider == "vb"
        vars["boxes"][box]["private_ip"].each do |network, ip|
          machine.vm.network "private_network",  
            ip:  ip,
            virtualbox__intnet: network
        end

        machine.vm.provider "virtualbox" do |v|
          v.memory = vars["boxes"][box]["memory"]
          v.cpus = vars["boxes"][box]["cpu"]
        end

      elsif provider == "vmware"
        vars["boxes"][box]["private_ip"].each do |network, ip|
          machine.vm.network "private_network",  
            ip:  ip
        end

        machine.vm.provider "vmware_desktop" do |v|
          v.vmx["memsize"] = vars["boxes"][box]["memory"]
          v.vmx["numvcpus"] = vars["boxes"][box]["cpu"]
        end
      end
    end
  end
end

# Create a forwarded port mapping which allows access to a specific port
# within the machine from a port on the host machine. In the example below,
# accessing "localhost:8080" will access port 80 on the guest machine.
# NOTE: This will enable public access to the opened port
# config.vm.network "forwarded_port", guest: 80, host: 8080

# Create a forwarded port mapping which allows access to a specific port
# within the machine from a port on the host machine and only allow access
# via 127.0.0.1 to disable public access
# config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

#      inventory[box] = ["#{box}_node"]
#      inventory["#{box}:vars"] = {"private_ip" => vars[box]["private_ip"],
#                       "use_config_path" => vars[box]["use_config_path"],
#                       "use_hosts_path" => vars[box]["use_hosts_path"]
#                        }
#      if inventory["#{box}:vars"]["use_config_path"]
#         inventory["#{box}:vars"]["config_path"] = vars[box]["config_path"]
#      else
#         inventory["#{box}:vars"]["config_repo"] = vars[box]["config_repo"]
#      end
#
#      if inventory["#{box}:vars"]["use_hosts_path"]
#         inventory["#{box}:vars"]["hosts_path"] = vars[box]["hosts_path"]
#      else
#         inventory["#{box}:vars"]["hosts_repo"] = vars[box]["hosts_repo"]
#      end

 
#     if machine_id == N-1
#        machine.vm.provision :ansible do |ansible|
#          puts "\n"+SEPARATOR+"Start Ansible Configuration"+SEPARATOR+"\n\n"
#          # Disable default limit to connect to all the machines
#          ansible.limit = "all"
#          ansible.groups = inventory
#          ansible.playbook = "../ansible-setup/topssim_setup.yaml"
#          ansible.tags = vars["ansible_tags"]
#        end
#      end

