---

- name: Copy component configs from path
  ansible.builtin.copy:
    src: "{{ config_path }}"
    dest: /root/open5gs/install/etc/open5gs
    mode: '0644'
  when: use_config_path 

- name: Clone component configs repo
  ansible.builtin.git: 
    repo: "{{ config_repo }}"
    dest: /root/open5gs/install/etc/open5gs
  when: not use_config_path

- name: Copy hosts file from path
  ansible.builtin.copy:
    src: "{{ hosts_path }}"
    dest: /etc/hosts
    remote_src: true
  become: yes
  when: use_hosts_path

- name: Clone hosts file from repo
  ansible.builtin.git: 
    repo: "{{ hosts_repo }}"
    dest: /tmp/hosts-repo
  when: not use_hosts_path 