---

# Using the command module is not ideal but makes it simpler here
- name: Create TUN device
  ansible.builtin.command: ip tuntap add name ogstun mode tun
  become: yes
  args:
    creates: /sys/class/net/ogstun
  tags: ['ogstun']
  
- name: Add Ipv4 Address to TUN
  ansible.builtin.command: ip addr add 10.45.0.1/16 dev ogstun
  become: yes
  failed_when: false
  changed_when: false
  tags: ['ogstun']
  
- name: Add Ipv6 Address to TUN
  ansible.builtin.command: ip addr add 2001:db8:cafe::1/48 dev ogstun
  become: yes
  failed_when: false
  changed_when: false
  tags: ['ogstun']
  
- name: Enable ogstun Interface
  ansible.builtin.command: ip link set ogstun up
  become: yes
  failed_when: false
  changed_when: false
  tags: ['ogstun']
  
- name: Install Open5GS Dependencies
  ansible.builtin.apt:
    name:
      - python3-pip 
      - python3-setuptools 
      - python3-wheel 
      - ninja-build 
      - build-essential 
      - flex 
      - bison 
      - git 
      - cmake 
      - libsctp-dev 
      - libgnutls28-dev 
      - libgcrypt-dev 
      - libssl-dev 
      - libmongoc-dev 
      - libbson-dev 
      - libyaml-dev 
      - libnghttp2-dev 
      - libmicrohttpd-dev 
      - libcurl4-gnutls-dev 
      - libnghttp2-dev 
      - libtins-dev 
      - libtalloc-dev 
      - meson
    state: present
    update_cache: yes
  become: yes
  tags: ['install_ogs']

- name: Install libidn depending on the system
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
    update_cache: true
  loop:
    - libidn-dev
    - libidn11-dev
  register: apt_result
  ignore_errors: true
  when: apt_result is not defined or apt_result.failed
  become: yes
  tags: ['install_ogs']

- name: Delete ogs dir if it exists
  ansible.builtin.file:
    path: /root/open5gs
    state: absent
  tags: ['install_ogs']

- name: Clone OGS Repo
  ansible.builtin.git: 
    repo: "{{ ogs_repo }}"
    dest: /root/open5gs
    single_branch: yes
    version: "{{ ogs_version }}"
  become: yes
  tags: ['install_ogs']

- name: Meson Build Open5GS
  ansible.builtin.command: 
    cmd: meson build --prefix=/root/open5gs/install
    chdir: /root/open5gs
  become: yes
  tags: ['install_ogs']

- name: Build Open5GS with Ninja
  shell: |
    cd /root/open5gs
    ninja -C build
  register: build_result   
  failed_when: build_result.rc != 0 
  become: yes
  tags: ['install_ogs']  
  
- name: Ninja Install Open5GS
  ansible.builtin.command: 
    cmd: ninja install
    chdir: /root/open5gs/build
  become: yes
  tags: ['install_ogs']

#- name: Install NodeJs prerequisites
#  ansible.builtin.apt:
#    name:
#      - ca-certificates
#      - curl
#      - gnupg
#    state: present
#    update_cache: true
#
#- name: Create keyrings directory
#  ansible.builtin.file:
#    path: /etc/apt/keyrings
#    state: directory
#    mode: '0755'
#
#- name: Download GPG key
#  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg -y
#  args:
#    creates: /etc/apt/keyrings/nodesource.gp
#
#- name: Add NodeSource repository
#  ansible.builtin.apt_repository:
#    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_major }}.x nodistro main"
#    state: present
#    filename: nodesource
#
#- name: Install Node.js
#  ansible.builtin.apt:
#    name: nodejs
#    state: present
#    update_cache: true
