---

# Using the command module is not ideal but makes it simpler here
- name: Create TUN device
  ansible.builtin.command: ip tuntap add name ogstun mode tun
  become: yes
  args:
    creates: /sys/class/net/ogstun
  
- name: Add Ipv4 Address to TUN
  ansible.builtin.command: ip addr add 10.45.0.1/16 dev ogstun
  become: yes
  failed_when: false
  changed_when: false
  
- name: Add Ipv6 Address to TUN
  ansible.builtin.command: ip addr add 2001:db8:cafe::1/48 dev ogstun
  become: yes
  failed_when: false
  changed_when: false
  
- name: Enable ogstun Interface
  ansible.builtin.command: ip link set ogstun up
  become: yes
  failed_when: false
  changed_when: false
  
- name: Install Open5GS Dependencies
  ansible.builtin.apt:
    name:
      - python3-pip 
      - python3-setuptools 
      - python3-wheel 
      - ninja-build 
      - build-essential 
      - flex 
      - bison 
      - git 
      - cmake 
      - libsctp-dev 
      - libgnutls28-dev 
      - libgcrypt-dev 
      - libssl-dev 
      - libmongoc-dev 
      - libbson-dev 
      - libyaml-dev 
      - libnghttp2-dev 
      - libmicrohttpd-dev 
      - libcurl4-gnutls-dev 
      - libnghttp2-dev 
      - libtins-dev 
      - libtalloc-dev 
      - meson
    state: present
    update_cache: yes

- name: Install libidn depending on the system
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
    update_cache: true
  loop:
    - libidn-dev
    - libidn11-dev
  register: apt_result
  ignore_errors: true
  when: apt_result is not defined or apt_result.failed

- name: Clone OGS Repo
  ansible.builtin.git: 
    repo: "{{ ogs_repo }}"
    dest: /root/open5gs
    single_branch: yes
    version: "{{ ogs_version }}"

- name: Meson Build Open5GS
  ansible.builtin.command: 
    cmd: meson build --prefix=/root/open5gs/install
    chdir: /root/open5gs

- name: Ninja Build Open5GS
  ansible.builtin.command: 
    cmd: ninja -C build
    chdir: /root/open5gs

- name: Ninja Install Open5GS
  ansible.builtin.command: 
    cmd: ninja install
    chdir: /root/open5gs/build