
---
all:
  vars:
    ansible_user: root
  children: 
    hplmn:  
      hosts:
        hplmn_node_1: 
          ansible_host: 216.128.176.167
        
    vplmn:  
      hosts:
        vplmn_node_1:
          ansible_host: 155.138.148.164
        