
---
all:
  vars:
    ansible_user: root
  children: 
    hplmn:  
      hosts:
        hplmn_node_1: 
          ansible_host: 155.138.136.15

        
    vplmn:  
      hosts:
        vplmn_node_1:
          ansible_host: 155.138.130.140
        