
---
all:
  vars:
    ansible_user: root
  children: 
    hplmn:  
      hosts:
        hplmn_node_1: 
          ansible_host: 149.248.51.214
    vplmn:  
      hosts:
        vplmn_node_1:
          ansible_host: 216.128.180.115
