---
# tasks file for Netplan Config

# set static ips for sepp link
# netplan apply
# test connection?

- name: Remove hardcoded address line
  ansible.builtin.replace:
    path: "{{ dest_netplan_path }}"
    regexp: '^\s+- "[\d\.]+/[\d]+"$'
    replace: ''

- name: Set static ips for sepp link 
  ansible.builtin.blockinfile:
    path: "{{ dest_netplan_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - enp8s0"
    insertafter: '      addresses:'
    block: "{{ enp8s0_block | indent(6, first=true) }}"

- name: Apply Netplan Config
  ansible.builtin.command:
    cmd: netplan apply
  become: yes
